# Generated by Django 3.2.4 on 2021-06-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='note',
            new_name='rating',
        ),
    ]
