# Generated by Django 3.2.4 on 2021-06-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_rename_note_feedback_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created_date',), 'verbose_name': 'feedback', 'verbose_name_plural': 'feedbacks'},
        ),
    ]
