# Generated by Django 3.2.4 on 2021-06-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created_date',), 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
