# Generated by Django 3.2.4 on 2021-07-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wilayas', '0001_initial'),
        ('services', '0004_auto_20210701_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilaya_service', to='wilayas.wilaya'),
        ),
    ]
