# Generated by Django 3.2.4 on 2021-07-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='confirmed',
            field=models.IntegerField(choices=[(2, 'Confirmed'), (1, 'Pending'), (0, 'Canceled')], default=1, verbose_name='Confirmation'),
        ),
    ]
